import { BadgeIconIds } from "@discord/components";
import { BadgeId } from "../stores/DiscordBadgeStore";

export default [
  'staff',
  'partner',
  'certified_moderator',
  'automod',
  'hypesquad',
  'bug_hunter_level_2',
  'bug_hunter_level_1',
  'hypesquad_house_3',
  'hypesquad_house_2',
  'hypesquad_house_1',
  'verified_developer',
  'active_developer',
  'bot_commands',
  'early_supporter',
  'premium_tenure_72_month_v2',
  'premium_tenure_60_month_v2',
  'premium_tenure_48_month_v2',
  'premium_tenure_36_month_v2',
  'premium_tenure_24_month_v2',
  'premium_tenure_12_month_v2',
  'premium_tenure_6_month_v2',
  'premium_tenure_3_month_v2',
  'premium_tenure_1_month_v2',
  'premium',
  'guild_booster_lvl9',
  'guild_booster_lvl8',
  'guild_booster_lvl7',
  'guild_booster_lvl6',
  'guild_booster_lvl5',
  'guild_booster_lvl4',
  'guild_booster_lvl3',
  'guild_booster_lvl2',
  'guild_booster_lvl1',
  'legacy_username',
  'quest_completed',
] as Array<BadgeId | BadgeIconIds>