export type Features =
  'ANIMATED_ICON' |
  'BANNER' |
  'COMMERCE' |
  'COMMUNITY' |
  'DISCOVERABLE' |
  'FEATURABLE' |
  'INVITE_SPLASH' |
  'MEMBER_VERIFICATION_GATE_ENABLED' |
  'NEWS' |
  'PARTNERED' |
  'PREVIEW_ENABLED' |
  'VANITY_URL' |
  'VERIFIED' |
  'VIP_REGIONS' |
  'WELCOME_SCREEN_ENABLED';