export const DiscordPermissionStrings = {
  ADD_REACTIONS: "Reactions",
  ADMINISTRATOR: "Admin",
  ATTACH_FILES: "Files",
  BAN_MEMBERS: "Ban",
  CHANGE_NICKNAME: "Nickname",
  CONNECT: "Connect",
  CREATE_INSTANT_INVITE: "Invite",
  DEAFEN_MEMBERS: "Deafen",
  EMBED_LINKS: "Embeds",
  KICK_MEMBERS: "Kick",
  MANAGE_CHANNELS: "Channels",
  // MANAGE_EMOJIS_AND_STICKERS: "Emojis/Stickers",
  MANAGE_GUILD_EXPRESSIONS: "Emojis/Stickers",
  MANAGE_GUILD: "Server",
  MANAGE_MESSAGES: "Messages",
  MANAGE_NICKNAMES: "Nicknames",
  MANAGE_ROLES: "Roles",
  MANAGE_WEBHOOKS: "Webhooks",
  MENTION_EVERYONE: "Mention",
  MOVE_MEMBERS: "Move",
  MUTE_MEMBERS: "Mute",
  PRIORITY_SPEAKER: "Priority",
  READ_MESSAGE_HISTORY: "History",
  SEND_MESSAGES: "Send",
  SEND_TTS_MESSAGES: "TTS",
  STREAM: "Stream/Video",
  SPEAK: "Speak",
  USE_EXTERNAL_EMOJIS: "External",
  USE_VAD: "VC Activity",
  VIEW_AUDIT_LOG: "Audit Log",
  VIEW_CHANNEL: "View",
  VIEW_GUILD_ANALYTICS: "Insights",
};

export type PermissionString = keyof typeof DiscordPermissionStrings;