export const enum MessageType {
  Default = 0,
  RecipientAdd = 1,
  RecipientRemove = 2,
  Call = 3,
  ChannelNameChange = 4,
  ChannelIconChange = 5,
  ChannelPinnedMessage = 6,
  UserJoin = 7,
  UserPremiumGuildSubscription = 8,
  UserPremiumGuildSubscriptionTier1 = 9,
  UserPremiumGuildSubscriptionTier2 = 10,
  UserPremiumGuildSubscriptionTier3 = 11,
  ChannelFollowAdd = 12,
  GuildStream = 13,
  GuildDiscoveryDisqualified = 14,
  GuildDiscoveryRequalified = 15,
  GuildDiscoveryGracePeriodInitialWarning = 16,
  GuildDiscoveryGracePeriodFinalWarning = 17,
  ThreadCreated = 18,
  Reply = 19,
  ChatInputCommand = 20,
  ThreadStarterMessage = 21,
  GuildInviteReminder = 22,
  ContextMenuCommand = 23
}