name: Check

on:
  push:
    branches:
      - master
    paths:
      - "**/*.ts"
      - "**/*.tsx"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.ts"
      - "**/*.tsx"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run check
